### ISSUE TITLE
Validations example

### ISSUE THREAD

**Issue by grk** [mbj/morpher#9]
As discussed on twitter, here's what I'd like to see an example for:

Given a hash

``` ruby
{
  "one" => "two",
  "foo" => ["bar", "baz"]
}
```

I'd like to validate, without transforming (I need the hash as output anyway) that keys "one" and "two" are present, no other keys are present, and that for key "one", only string values are allowed, and for the key "foo" only an array of strings is allowed.

thanks :)

**Comment by mbj** [comment]
I'm closing this as I'm unlikely to put up examples any time soon.
